= Vegan Kimchi with Mushrooms and Seaweed
:date: 2025-08-07

== Introduction
I have not looked exhaustively, but every vegan kimchi recipe I've encountered has not come close to imitating a traditional kimchi, where fish sauce and/or salted shrimp are used to bring deep umami to the dish.
What else has a lot of that in Asian cooking?
Mushrooms and seaweed!
Making a stock of these and reducing it gives you something that, in the broadest strokes, functions like fish sauce.

== Ingredients

* 5-7 dried shiitakes
* 3"x3" sheet of kombu
* 1 medium head napa cabbage
* 1 carrot
* 1 small daikon
* 1/2 medium yellow onion
* 6-8 cloves garlic (or to taste)
* 2 tsp ginger (about a 0.5" slice)
* 2 scallions
* 2 tbsp glutinous rice flour (any other starch would work fine too)
* 1 tsp sugar
* 1/3 cup coarse gochugaru (Korean red chili flakes) (or to taste)
* coarse kosher or sea salt

== Recipe
               
1. The night before, soak the shiitakes and the kombu in a quart of filtered water. Use a cartouche or some other means to ensure that the mushrooms remain submerged.
2. Slice the cabbage into radial eighths and then slice each eighth into bite-sized pieces.
3. In a large bowl, combine cabbage with 1/4 cup of salt and work into the leaves by hand. Let sit for 2-3 hours, mixing intermittently at the beginning to ensure even salting.
4. Separately, julienne the carrot, daikon, and the greens of the scallions. Combine in a separate bowl with 1tbsp of salt and also mix intermittently.
5. Strain mushrooms and kombu sheet out of the stock and discard. Place stock over low heat, uncovered, in a saucepan, and reduce at a temperature well below boiling (targeting 160F-180F) until reduced at least by half in volume.
6. In a blender, combine all remaining vegetables (ginger, garlic, onion, scallion whites) and just enough of the stock to have it come together into a smooth paste.
7. Once the stock has reduced, sift glutinous rice flour into it, stirring vigorously so that clumps do not form. Stir until it becomes viscous, almost like a loose dough. Add more flour if necessary. Let stand to cool.
8. Rinse the salted vegetables thoroughly under cold water to remove excess salt, and dry by using a salad spinner, patting with a towel, or squeezing by hand.
9. Once cool, combine blended vegetable paste, stock and rice flour paste, sugar, and gochugaru in a large bowl. Mix together until homogeneous.
10. Combine rinsed salted vegetables with paste.
11. Place in fermenter and ensure that liquid covers all solids. Let stand at room temperature (72F or so) for at least a day, then refrigerate to slow fermentation.

== Notes
* If you don't have a blender, a coarse mince should be just fine.
* For an extra bump of umami and complexity, during the stock reduction, you may add some miso or doenjang.
* I haven't tried this, but adding a bit of apple cider vinegar or maesil cheong to the paste may help bring some brighter notes imitating salted shrimp.

++++
<script>
var disqus_config = function () {
  this.page.url = 'https://lgessler.com/recipes/vegan-kimchi.html';
  this.page.identifier = '/recipes/vegan-kimchi';
};
(function() { // DON'T EDIT BELOW THIS LINE
  var d = document, s = d.createElement('script');
  s.src = 'https://lgessler-com.disqus.com/embed.js';
  s.setAttribute('data-timestamp', +new Date());
  (d.head || d.body).appendChild(s);
})();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
++++ 
